export const TELEGRAM_HELP = [
  "Quick Start",
  "",
  "/preset technical_ru",
  "/models",
  "/settings",
  "",
  "Chat",
  "- /mode auto|general|code|hypothesis",
  "- /language auto|ru|en",
  "- /use <providerId> [modelOrAlias]",
  "",
  "Models",
  "- /models",
  "- /all_models",
  "- /load_model <modelOrAlias>",
  "- /unload_model <modelOrAlias|instanceId>",
  "",
  "Debate",
  "- /debate on|off",
  "- /debate profile <general|technical|product|research|security>",
  "- /debate support <providerId> [modelOrAlias]",
  "- /debate attack <providerId> [modelOrAlias]",
  "- /debate judge <local|providerId> [modelOrAlias]",
  "",
  "Presets",
  "- /presets",
  "- /preset chat_ru",
  "- /preset debate_ru",
  "- /preset technical_ru",
  "- /preset security_ru",
  "",
  "Other",
  "- /providers",
  "- /settings",
  "- /reset_settings"
].join("\n");
